Invoking command in '/home/aziz/microros_ws1/firmware/mcu_ws/uros/tracetools/tracetools_trace': PYTHONPATH=/home/aziz/microros_ws1/firmware/mcu_ws/install/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py egg_info --egg-base ../../../build/tracetools_trace build --build-base /home/aziz/microros_ws1/firmware/mcu_ws/build/tracetools_trace/build install --prefix /home/aziz/microros_ws1/firmware/mcu_ws/install --record /home/aziz/microros_ws1/firmware/mcu_ws/build/tracetools_trace/install.log --single-version-externally-managed
Invoked command in '/home/aziz/microros_ws1/firmware/mcu_ws/uros/tracetools/tracetools_trace' returned '0': PYTHONPATH=/home/aziz/microros_ws1/firmware/mcu_ws/install/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py egg_info --egg-base ../../../build/tracetools_trace build --build-base /home/aziz/microros_ws1/firmware/mcu_ws/build/tracetools_trace/build install --prefix /home/aziz/microros_ws1/firmware/mcu_ws/install --record /home/aziz/microros_ws1/firmware/mcu_ws/build/tracetools_trace/install.log --single-version-externally-managed
